/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class redlib_RFILE_CompressFile */

#ifndef _Included_redlib_RFILE_CompressFile
#define _Included_redlib_RFILE_CompressFile
#ifdef __cplusplus
extern "C" {
#endif
#undef redlib_RFILE_CompressFile_EOF
#define redlib_RFILE_CompressFile_EOF -1L
/*
 * Class:     redlib_RFILE_CompressFile
 * Method:    read
 * Signature: (I)[C
 */
JNIEXPORT jcharArray JNICALL Java_redlib_RFILE_CompressFile_read
  (JNIEnv *, jobject, jint);

/*
 * Class:     redlib_RFILE_CompressFile
 * Method:    write
 * Signature: ([C)I
 */
JNIEXPORT jint JNICALL Java_redlib_RFILE_CompressFile_write
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     redlib_RFILE_CompressFile
 * Method:    flush
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_redlib_RFILE_CompressFile_flush
  (JNIEnv *, jobject);

/*
 * Class:     redlib_RFILE_CompressFile
 * Method:    open
 * Signature: ([C[C)V
 */
JNIEXPORT void JNICALL Java_redlib_RFILE_CompressFile_open
  (JNIEnv *, jobject, jcharArray, jcharArray);

/*
 * Class:     redlib_RFILE_CompressFile
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_redlib_RFILE_CompressFile_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
