/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class redlib_RFILE_CompressFileException */

#ifndef _Included_redlib_RFILE_CompressFileException
#define _Included_redlib_RFILE_CompressFileException
#ifdef __cplusplus
extern "C" {
#endif
#undef redlib_RFILE_CompressFileException_serialVersionUID
#define redlib_RFILE_CompressFileException_serialVersionUID -3042686055658047285LL
#undef redlib_RFILE_CompressFileException_serialVersionUID
#define redlib_RFILE_CompressFileException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
