/* Automatically generated by po2tbl.sed from viaduct.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"required:", 2},
  {"dest", 3},
  {"port", 4},
  {"src", 5},
  {"show all", 6},
  {"destination", 7},
  {"unknown", 8},
  {"source", 9},
  {"time interval", 10},
  {"verbose", 11},
  {"extra verbose", 12},
  {"even more extra verbose", 13},
  {"Error opening: ", 14},
  {"tap open", 15},
  {"interval set", 16},
  {"thread created", 17},
  {"chardev dest", 18},
  {"chardev src", 19},
  {"timer", 20},
  {"No serial component installed", 21},
  {"socket", 22},
  {"bind", 23},
  {"listen", 24},
  {"accept", 25},
  {"ERROR inet_aton()", 26},
  {"PASSED", 27},
  {"ERROR passed through", 28},
  {"inet_aton false", 29},
  {"Anything happen?", 30},
  {"No such file or directory", 31},
  {"no socket", 32},
  {"no bind", 33},
  {"no listen", 34},
  {"Hmalloc failed", 35},
  {"Host lookup failed", 36},
  {"Eh? It's an address, not an IP number", 37},
};

int _msg_tbl_length = 37;
